[package]
name = "varfish-server-worker"
version = "0.1.0"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Rust-based workers for varfish-server"
license-file = "LICENSE.md"
homepage = "https://github.com/bihealth/varfish-server-workers"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.68", features = ["backtrace"] }
clap = { version = "4.1.1", features = ["derive"] }
clap-verbosity-flag = "2.0.0"
console = "0.15.5"
thiserror = "1.0.38"

[[bin]]
name = "varfish-server-worker"
path = "src/main.rs"
