[package]
name = "varfish-server-worker"
version = "0.1.0"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Rust-based workers for varfish-server"
license-file = "LICENSE.md"
homepage = "https://github.com/bihealth/varfish-server-workers"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { version = "1.0.68", features = ["backtrace"] }
bio = "1.1.0"
byte-unit = "4.0.18"
clap = { version = "4.1.1", features = ["derive"] }
clap-verbosity-flag = "2.0.0"
console = "0.15.5"
csv = "1.1.6"
flate2 = "1.0.25"
procfs = "0.14.2"
serde = { version = "1.0.152", features = ["serde_derive"] }
thiserror = "1.0.38"
thousands = "0.2.0"

[[bin]]
name = "varfish-server-worker"
path = "src/main.rs"
