[package]
name = "varfish-server-workers"
version = "0.1.0"
authors = ["Manuel Holtgrewe <manuel.holtgrewe@bih-charite.de>"]
description = "Rust-based workers for varfish-server"
license-file = "LICENSE.md"
homepage = "https://github.com/bihealth/varfish-server-workers"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "varfish-server-workers"
path = "src/main.rs"