name: install-flatbuffers
description: Install flatbuffers

runs:
  using: "composite"
  steps:
    - name: Cache flatbuffers installation
      id: cache-flatbuffers-installation
      uses: actions/cache@v3
      env:
        cache-name: cache-install-flatbuffers
      with:
        path: ~/.local/share/flatbuffers
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        restore-keys: |
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - if: ${{ steps. cache-flatbuffers-installation.outputs.cache-hit != 'true' }}
      name: Install flatbuffers
      shell: bash
      run: |
        mkdir -p utils/var
        cd utils/var
        git clone https://github.com/google/flatbuffers.git
        cd flatbuffers
        git checkout v22.12.06
        cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=$HOME/.local/share/flatbuffers
        make
        ./flattests
        sudo make install
        export PATH=$PATH:$HOME/.local/share/flatbuffers/bin
        flatc --version

    - name: Make flatc available in PATH
      shell: bash
      run: |
        echo "$HOME/.local/share/flatbuffers/bin" >> $GITHUB_PATH
